### ISSUE TITLE
Not working in 2023?

### ISSUE THREAD

**Issue by VoDaCZx** [adriantc/UTF-8SubtitlesConverter.bundle#5]
Hello ...
I dont know what i doing wrong but i have your plugin in the agents, but nothing happened with any subtitles...
Where can be a problem?? Can i send u any logs??

Thanks David

**Comment by adriantc** [comment]
Hi David.

First of all you must know that this plugin is not compatible with the new agents so you have to use the old agents (legacy) on the movie libraries you want to use subtitle conversion. (an example here: https://ibb.co/sJx87Fp)
Second in the Agents settings in the Plex server the UTF-8 subtitles converter plugin must be the first in order to get applied before any scan gets done. (an example here: https://ibb.co/mbGYQ0M)

Let me know if that does the trick for you.

Adrian

**Comment by VoDaCZx** [comment]
Hello Adrian...
Legacy Agents.... Ahh there was a problem.... :) because i have it in first order and i cant find the way how to make to work it... 
Many thanks!!! It spent many hours of converting thru subtitle editor ;) 
My version of server is 1.32.4.7195

Thanks again!!!
